version: '3.9'

services:
  music_social_app:
    container_name: music-social-app
    build: .
    image: music-social-app
    ports:
      - '8080:3000'
    environment:
      - PG_DB=music-social
      - PG_USER=postgres
      - PG_PASSWORD=12345
      - PG_HOST=db
      - PG_PORT=5432
    depends_on:
      - db

  db:
    container_name: music-social-db
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=music-social
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}
