version: '3.9'

services:
  music_social_app:
    container_name: music-social-app
    build: .
    image: music-social-app
    ports:
      - '8080:3000'
    environment:
      - NODE_ENV=docker_development
      - CLIENT_ORIGIN=http://localhost:3000
      - PG_DB=music-social-network
      - PG_USER=postgres
      - PG_PASSWORD=12345
      - PG_HOST=db
      - PG_PORT=5432
      - JWT_ACCESS_SECRET=EJmVoJU6jzo7cLkJztS1gOOyXVvNkn05KDbxuhAJ4tizs77QSG
    depends_on:
      - db

  db:
    container_name: music-social-db
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=music-social-network
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}
